name: Update mesonet database

on: 
  push:
    branches:
    - "db-test"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          git diff ${{github.event.before}} ${{github.sha}}