name: Update mesonet database

on: 
  push:
    branches:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # checkout full tree
          fetch-depth: 0
      # Setup python
      - uses: actions/setup-python@v5
      - run: |
          git diff --name-only ${{github.event.before}} ${{github.sha}} -- csv_data > changes.txt
      - name: Update database
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run:
          pip3 install psycopg2 && python3 $GITHUB_WORKSPACE/scripts/update_db.py
